# Generated by Django 2.2.7 on 2021-03-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_path', models.TextField()),
                ('slug', models.TextField(unique=True)),
            ],
        ),
    ]
